# Generated by Django 3.1.14 on 2023-08-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiantes_trabajo_grado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('Numero_de_Identificación', models.PositiveIntegerField()),
                ('nombre_del_Proyecto', models.CharField(max_length=200)),
                ('programa_Académico', models.CharField(blank=True, choices=[('DERECHO', 'Derecho'), ('TRABAJO SOCIAL', 'Trabajo Social'), ('COMUNICACIÓN SOCIAL', 'Comunicación Social'), ('PSICOLOGÍA', 'Psicología'), ('MERCADEO', 'Mercadeo'), ('CONTADURIA', 'Contaduría Pública'), ('NEGOCIOS INTERNACIONALES', 'Administración de Negocios Internacionales'), ('LICENCIATURA EN LITERATURA', 'Licenciatura en Literatura'), ('LICENCIATURA EN MATEMATICÁS', 'Licenciatura en Matemáticas'), ('LICENCIATURA EN EDUCACIÓN INFANTIL', 'Licenciatura en Educación Infantil'), ('LICENCIATURA EN EDUCACIÓN BÁSICA PRIMARIA', 'Licenciatura en Educación Básica Primaria'), ('ENFERMERÍA', 'Enfermería'), ('TERAPIA OCUPACIONAL', 'Terapia Ocupacional'), ('FISIOTERAPIA', 'Fisioterapia'), ('NUTRICIÓN Y DIETÉTICA', 'Nutrición y Dietética'), ('INGENIERÍA MECATRÓNICA', 'Ingeniería Mecatrónica'), ('INGENIERÍA CIVIL', 'Ingeniería Civil'), ('INGENIERÍA DE SISTEMAS', 'Ingeniería de Sistemas'), ('INGENIERÍA AMBIENTAL', 'Ingeniería Ambiental'), ('INGENIERÍA DE PROCESOS', 'Ingeniería de Procesos')], max_length=41, null=True)),
                ('nombre_Asesor', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('teléfono', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Estudiante Trabajo de Grado',
                'verbose_name_plural': 'Estudiantes Trabajo de Grado',
            },
        ),
        migrations.CreateModel(
            name='eventos_Relacionados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventos_Nacionales', models.CharField(max_length=1000, verbose_name='Eventos Nacionales')),
                ('eventos_Internacionales', models.CharField(max_length=1000, verbose_name='Eventos Internacionales')),
                ('reconocimientos', models.CharField(blank=True, max_length=1000, verbose_name='Reconocimientos')),
                ('vinculados_inveProfesorales', models.CharField(max_length=1000, verbose_name='Vinculados InveProfesorales')),
                ('Grupo_de_Investigación', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.grupos_de_investigacion')),
            ],
            options={
                'verbose_name': 'Evento Relacionado',
                'verbose_name_plural': 'Eventos Relacionados',
            },
        ),
        migrations.CreateModel(
            name='proyecto_semillerista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_Proyecto', models.PositiveIntegerField(verbose_name='Codigo Proyecto')),
                ('Nombre_del_Proyecto', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('estado_del_Proyecto', models.CharField(max_length=100, verbose_name='Estado del Proyecto')),
                ('linea_de_Investigacion', models.CharField(max_length=100, verbose_name='Linea de Investigación')),
                ('convalidado', models.BooleanField(default=True, verbose_name='Convalidado')),
            ],
            options={
                'verbose_name': 'Proyecto Semillerista',
                'verbose_name_plural': 'Proyectos Semilleristas',
            },
        ),
        migrations.CreateModel(
            name='semillerista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.PositiveIntegerField(verbose_name='Cedula')),
                ('semillero', models.CharField(max_length=30, verbose_name='Semillero')),
                ('codigo_Proyecto', models.PositiveIntegerField(verbose_name='Codigo del Proyecto')),
                ('fecha_Vinculacion', models.DateField(verbose_name='Fecha Vonculación')),
                ('nombre_Completo', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('codigo_Estudiantil', models.IntegerField(verbose_name='Codigo Estudiantil')),
                ('facultad_adscrito', models.CharField(choices=[('CIENCIAS DE LA SALUD', 'Ciencias de la Salud'), ('EDUCACIÓN', 'Educación'), ('FACULTAD DE INGENIERIA', 'Facultad de Ingenieria'), ('HUMANIDADES Y CIENCIAS SOCIALES', 'Humanidades y Ciencias Sociales'), ('CCIENCIAS CONTABLES, ECONÓMIA', 'Ciencias Contables, Económia')], default='I', max_length=31, verbose_name='Facultad Adscrito')),
                ('programa', models.CharField(blank=True, choices=[('DERECHO', 'Derecho'), ('TRABAJO SOCIAL', 'Trabajo Social'), ('COMUNICACIÓN SOCIAL', 'Comunicación Social'), ('PSICOLOGÍA', 'Psicología'), ('MERCADEO', 'Mercadeo'), ('CONTADURIA', 'Contaduría Pública'), ('NEGOCIOS INTERNACIONALES', 'Administración de Negocios Internacionales'), ('LICENCIATURA EN LITERATURA', 'Licenciatura en Literatura'), ('LICENCIATURA EN MATEMATICÁS', 'Licenciatura en Matemáticas'), ('LICENCIATURA EN EDUCACIÓN INFANTIL', 'Licenciatura en Educación Infantil'), ('LICENCIATURA EN EDUCACIÓN BÁSICA PRIMARIA', 'Licenciatura en Educación Básica Primaria'), ('ENFERMERÍA', 'Enfermería'), ('TERAPIA OCUPACIONAL', 'Terapia Ocupacional'), ('FISIOTERAPIA', 'Fisioterapia'), ('NUTRICIÓN Y DIETÉTICA', 'Nutrición y Dietética'), ('INGENIERÍA MECATRÓNICA', 'Ingeniería Mecatrónica'), ('INGENIERÍA CIVIL', 'Ingeniería Civil'), ('INGENIERÍA DE SISTEMAS', 'Ingeniería de Sistemas'), ('INGENIERÍA AMBIENTAL', 'Ingeniería Ambiental'), ('INGENIERÍA DE PROCESOS', 'Ingeniería de Procesos')], max_length=41, null=True, verbose_name='Programa')),
                ('semestre', models.PositiveIntegerField(blank=True, verbose_name='Semestre')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('telefono', models.IntegerField(blank=True, verbose_name='Telefono')),
                ('financiacion_interna', models.PositiveIntegerField(verbose_name='Financiación Interna')),
                ('financiacion_externa', models.PositiveIntegerField(blank=True, verbose_name='Financiación Externa')),
                ('relaciones_Politicas_Internacionales', models.CharField(max_length=200, verbose_name='Relaciones Politicas Internacionales')),
                ('Describir_Tema', models.CharField(max_length=150, verbose_name='Describir Tema')),
                ('reto', models.CharField(max_length=150, verbose_name='Reto')),
                ('eventos_Relacionados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_investigativa.eventos_relacionados')),
                ('proyectos_Vinculados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_investigativa.proyecto_semillerista')),
            ],
            options={
                'verbose_name': 'Semillerista',
                'verbose_name_plural': 'Semilleristas',
            },
        ),
        migrations.CreateModel(
            name='semillero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('coordinador', models.CharField(max_length=100, verbose_name='Coordinador')),
                ('facultad', models.CharField(choices=[('CIENCIAS DE LA SALUD', 'Ciencias de la Salud'), ('EDUCACIÓN', 'Educación'), ('FACULTAD DE INGENIERIA', 'Facultad de Ingenieria'), ('HUMANIDADES Y CIENCIAS SOCIALES', 'Humanidades y Ciencias Sociales'), ('CCIENCIAS CONTABLES, ECONÓMIA', 'Ciencias Contables, Económia')], default='', max_length=31, verbose_name='Facultad')),
                ('programa', models.CharField(blank=True, max_length=50, verbose_name='Programa')),
                ('lider_Semillero', models.CharField(max_length=50, verbose_name='Lider Semillero')),
                ('fecha_de_Creacion', models.DateField(verbose_name='Fecha de Creación')),
                ('linea_Investigacion', models.CharField(max_length=100, verbose_name='Linea de Investigación')),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('integrantes_Activos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes_semilleristas', to='formacion_investigativa.semillerista')),
            ],
            options={
                'verbose_name': 'Semillero',
                'verbose_name_plural': 'Semilleros',
            },
        ),
        migrations.CreateModel(
            name='pasantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('proyecto_de_investigacion', models.CharField(max_length=200, verbose_name='Proyecto de Investigación')),
                ('anio_vinculacion', models.PositiveIntegerField(verbose_name='Año Vinculación')),
                ('nombre_Asesor', models.CharField(max_length=50, verbose_name='Nombre del Asesor')),
                ('programa_academico', models.CharField(blank=True, choices=[('DERECHO', 'Derecho'), ('TRABAJO SOCIAL', 'Trabajo Social'), ('COMUNICACIÓN SOCIAL', 'Comunicación Social'), ('PSICOLOGÍA', 'Psicología'), ('MERCADEO', 'Mercadeo'), ('CONTADURIA', 'Contaduría Pública'), ('NEGOCIOS INTERNACIONALES', 'Administración de Negocios Internacionales'), ('LICENCIATURA EN LITERATURA', 'Licenciatura en Literatura'), ('LICENCIATURA EN MATEMATICÁS', 'Licenciatura en Matemáticas'), ('LICENCIATURA EN EDUCACIÓN INFANTIL', 'Licenciatura en Educación Infantil'), ('LICENCIATURA EN EDUCACIÓN BÁSICA PRIMARIA', 'Licenciatura en Educación Básica Primaria'), ('ENFERMERÍA', 'Enfermería'), ('TERAPIA OCUPACIONAL', 'Terapia Ocupacional'), ('FISIOTERAPIA', 'Fisioterapia'), ('NUTRICIÓN Y DIETÉTICA', 'Nutrición y Dietética'), ('INGENIERÍA MECATRÓNICA', 'Ingeniería Mecatrónica'), ('INGENIERÍA CIVIL', 'Ingeniería Civil'), ('INGENIERÍA DE SISTEMAS', 'Ingeniería de Sistemas'), ('INGENIERÍA AMBIENTAL', 'Ingeniería Ambiental'), ('INGENIERÍA DE PROCESOS', 'Ingeniería de Procesos')], default='INGENIERÍA DE SISTEMAS', max_length=41, null=True, verbose_name='Programa Académico')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('telefono', models.PositiveIntegerField(blank=True, verbose_name='Teléfono')),
                ('Grupo_de_Investigación_al_que_Pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.grupos_de_investigacion')),
                ('investigadores_vinculados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.investigadores')),
            ],
            options={
                'verbose_name': 'Pasante',
                'verbose_name_plural': 'Pasantes',
            },
        ),
        migrations.CreateModel(
            name='jovenes_investigadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('proyecto_de_investigación', models.CharField(max_length=200)),
                ('año_vinculación', models.PositiveIntegerField()),
                ('nombre_Asesor', models.CharField(max_length=50)),
                ('programa_académico', models.CharField(blank=True, choices=[('DERECHO', 'Derecho'), ('TRABAJO SOCIAL', 'Trabajo Social'), ('COMUNICACIÓN SOCIAL', 'Comunicación Social'), ('PSICOLOGÍA', 'Psicología'), ('MERCADEO', 'Mercadeo'), ('CONTADURIA', 'Contaduría Pública'), ('NEGOCIOS INTERNACIONALES', 'Administración de Negocios Internacionales'), ('LICENCIATURA EN LITERATURA', 'Licenciatura en Literatura'), ('LICENCIATURA EN MATEMATICÁS', 'Licenciatura en Matemáticas'), ('LICENCIATURA EN EDUCACIÓN INFANTIL', 'Licenciatura en Educación Infantil'), ('LICENCIATURA EN EDUCACIÓN BÁSICA PRIMARIA', 'Licenciatura en Educación Básica Primaria'), ('ENFERMERÍA', 'Enfermería'), ('TERAPIA OCUPACIONAL', 'Terapia Ocupacional'), ('FISIOTERAPIA', 'Fisioterapia'), ('NUTRICIÓN Y DIETÉTICA', 'Nutrición y Dietética'), ('INGENIERÍA MECATRÓNICA', 'Ingeniería Mecatrónica'), ('INGENIERÍA CIVIL', 'Ingeniería Civil'), ('INGENIERÍA DE SISTEMAS', 'Ingeniería de Sistemas'), ('INGENIERÍA AMBIENTAL', 'Ingeniería Ambiental'), ('INGENIERÍA DE PROCESOS', 'Ingeniería de Procesos')], default='INGENIERÍA DE SISTEMAS', max_length=41, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('teléfono', models.PositiveIntegerField(blank=True)),
                ('Grupo_de_Investigación_al_que_Pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.grupos_de_investigacion')),
                ('investigadores_vinculados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.investigadores')),
            ],
            options={
                'verbose_name': 'joven investigador',
                'verbose_name_plural': 'jovenes Investigadores',
            },
        ),
        migrations.CreateModel(
            name='coInvestigadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('proyecto_de_investigacion', models.CharField(max_length=200, verbose_name='Proyecto de Investigación')),
                ('anio_vinculacion', models.PositiveIntegerField(verbose_name='Año Vinculación')),
                ('nombre_Asesor', models.CharField(max_length=50, verbose_name='Nombre del Asesor')),
                ('programa_academico', models.CharField(blank=True, choices=[('DERECHO', 'Derecho'), ('TRABAJO SOCIAL', 'Trabajo Social'), ('COMUNICACIÓN SOCIAL', 'Comunicación Social'), ('PSICOLOGÍA', 'Psicología'), ('MERCADEO', 'Mercadeo'), ('CONTADURIA', 'Contaduría Pública'), ('NEGOCIOS INTERNACIONALES', 'Administración de Negocios Internacionales'), ('LICENCIATURA EN LITERATURA', 'Licenciatura en Literatura'), ('LICENCIATURA EN MATEMATICÁS', 'Licenciatura en Matemáticas'), ('LICENCIATURA EN EDUCACIÓN INFANTIL', 'Licenciatura en Educación Infantil'), ('LICENCIATURA EN EDUCACIÓN BÁSICA PRIMARIA', 'Licenciatura en Educación Básica Primaria'), ('ENFERMERÍA', 'Enfermería'), ('TERAPIA OCUPACIONAL', 'Terapia Ocupacional'), ('FISIOTERAPIA', 'Fisioterapia'), ('NUTRICIÓN Y DIETÉTICA', 'Nutrición y Dietética'), ('INGENIERÍA MECATRÓNICA', 'Ingeniería Mecatrónica'), ('INGENIERÍA CIVIL', 'Ingeniería Civil'), ('INGENIERÍA DE SISTEMAS', 'Ingeniería de Sistemas'), ('INGENIERÍA AMBIENTAL', 'Ingeniería Ambiental'), ('INGENIERÍA DE PROCESOS', 'Ingeniería de Procesos')], default='INGENIERÍA DE SISTEMAS', max_length=41, null=True, verbose_name='Programa Académico')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('telefono', models.PositiveIntegerField(blank=True, verbose_name='Teléfono')),
                ('Grupo_de_Investigación_al_que_Pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.grupos_de_investigacion')),
                ('investigadores_vinculados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.investigadores')),
            ],
            options={
                'verbose_name': 'CoInvestigador',
                'verbose_name_plural': 'CoInvestigadores',
            },
        ),
        migrations.CreateModel(
            name='auxiliares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('proyecto_de_investigacion', models.CharField(max_length=200, verbose_name='Proyecto de Investigación')),
                ('anio_vinculacion', models.PositiveIntegerField(verbose_name='Año de Vinculación')),
                ('nombre_Asesor', models.CharField(max_length=50, verbose_name='Nombre Asesor')),
                ('programa_academico', models.CharField(blank=True, choices=[('DERECHO', 'Derecho'), ('TRABAJO SOCIAL', 'Trabajo Social'), ('COMUNICACIÓN SOCIAL', 'Comunicación Social'), ('PSICOLOGÍA', 'Psicología'), ('MERCADEO', 'Mercadeo'), ('CONTADURIA', 'Contaduría Pública'), ('NEGOCIOS INTERNACIONALES', 'Administración de Negocios Internacionales'), ('LICENCIATURA EN LITERATURA', 'Licenciatura en Literatura'), ('LICENCIATURA EN MATEMATICÁS', 'Licenciatura en Matemáticas'), ('LICENCIATURA EN EDUCACIÓN INFANTIL', 'Licenciatura en Educación Infantil'), ('LICENCIATURA EN EDUCACIÓN BÁSICA PRIMARIA', 'Licenciatura en Educación Básica Primaria'), ('ENFERMERÍA', 'Enfermería'), ('TERAPIA OCUPACIONAL', 'Terapia Ocupacional'), ('FISIOTERAPIA', 'Fisioterapia'), ('NUTRICIÓN Y DIETÉTICA', 'Nutrición y Dietética'), ('INGENIERÍA MECATRÓNICA', 'Ingeniería Mecatrónica'), ('INGENIERÍA CIVIL', 'Ingeniería Civil'), ('INGENIERÍA DE SISTEMAS', 'Ingeniería de Sistemas'), ('INGENIERÍA AMBIENTAL', 'Ingeniería Ambiental'), ('INGENIERÍA DE PROCESOS', 'Ingeniería de Procesos')], default='INGENIERÍA DE SISTEMAS', max_length=41, null=True, verbose_name='Programa Académico')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('telefono', models.PositiveIntegerField(blank=True, verbose_name='Teléfono')),
                ('Grupo_de_Investigación_al_que_Pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.grupos_de_investigacion')),
                ('investigadores_vinculados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investigadores.investigadores')),
            ],
            options={
                'verbose_name': 'Auxiliar',
                'verbose_name_plural': 'Auxiliares',
            },
        ),
    ]
