# Generated by Django 3.1.14 on 2023-08-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='convocatorias_externas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('INACTIVA', 'INACTIVA')], default='ACTIVA', max_length=10, verbose_name='Estado')),
                ('nombre_convocatoria', models.CharField(max_length=200, verbose_name='Nombre de la Convocatoria')),
                ('fecha_de_Inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_Finalizacion', models.DateField(verbose_name='Fecha de Finalización')),
                ('enlace_Externo', models.URLField(verbose_name='Enlace Externo')),
                ('monto_ganadores', models.PositiveIntegerField(verbose_name='Monto Ganadores')),
                ('documentos_del_Proceso', models.FileField(upload_to='media/convocatorias_externa/', verbose_name='Subir Documentos del Proceso')),
            ],
            options={
                'verbose_name': 'Convocatoria Externa',
                'verbose_name_plural': 'Convocatorias Externas',
            },
        ),
        migrations.CreateModel(
            name='convocatorias_internas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('INACTIVA', 'INACTIVA')], default='ACTIVA', max_length=10, verbose_name='Estado')),
                ('nombre_convocatoria', models.CharField(max_length=200, verbose_name='Nombre de la Convocatoria')),
                ('fecha_de_Inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_Finalizacion', models.DateField(verbose_name='Fecha de Finalización')),
                ('monto_ganadores', models.PositiveIntegerField(verbose_name='Monto Ganadores')),
                ('documentos_del_Proceso', models.FileField(upload_to='media/convocatorias_interna/', verbose_name='Subir documentos del Proceso')),
            ],
            options={
                'verbose_name': 'Convocatoria Interna',
                'verbose_name_plural': 'Convocatorias Internas',
            },
        ),
    ]
