# Generated by Django 3.1.14 on 2023-09-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_actividad1_Objetivo1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actividad de objetivo 1'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_actividad1_Objetivo2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actividad de objetivo 2'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_actividad1_Objetivo3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actividad de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_actividad2_Objetivo1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actividad 2 de objetivo 1'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_actividad2_Objetivo2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actividad 2 de objetivo 2'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_actividad2_Objetivo3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actividad 2 de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_actividad3_Objetivo1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actividad 3 de objetivo 1'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_actividad3_Objetivo2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actividad 3 de objetivo 2'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_actividad3_Objetivo3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actividad 3 de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_actividad4_Objetivo3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Actividad 4 de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_entregainformafinal',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Informe final'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_entregainformeavance',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Informe de avance'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_mes1_Objetivo1',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mes de objetivo 1'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_mes1_Objetivo2',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mes de objetivo 2'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_mes1_Objetivo3',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mes de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_mes2_Objetivo1',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mes 2 de objetivo 1'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_mes2_Objetivo2',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mes 2 de objetivo 2'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_mes2_Objetivo3',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mes 2 de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_mes3_Objetivo1',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mes 3 de objetivo 1'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_mes3_Objetivo2',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mes 3 de objetivo 2'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_mes3_Objetivo3',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mes 3 de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_mes4_Objetivo3',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Mes 4 de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_producto1_Objetivo1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Producto de objetivo 1'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_producto1_Objetivo2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Producto de objetivo 2'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_producto1_Objetivo3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Producto de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_producto2_Objetivo1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Producto 2 de objetivo 1'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_producto2_Objetivo2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Producto 2 de objetivo 2'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_producto2_Objetivo3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Producto 2 de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_producto3_Objetivo1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Producto 3 de objetivo 1'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_producto3_Objetivo2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Producto 3 de objetivo 2'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_producto3_Objetivo3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Producto 3 de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_producto4_Objetivo3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Producto 4 de objetivo 3'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_productos_Estrategiadivulgacion',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Estrategia de divulgación'),
        ),
    ]
