# Generated by Django 3.1.14 on 2023-09-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0002_auto_20230901_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_referecias',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Referecias'),
        ),
    ]
