# Generated by Django 3.1.14 on 2023-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0003_proyecto_tecnologico_txt_referecias'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_campoAcademico_Indicador',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Indicador Academico'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_desarrolloTecnologico_Indicador',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Indicador Tecnologico'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_economicos_Indicador',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Indicador Economico'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_educativo_Indicador',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Indicador Educativo'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_simbolico_Indicador',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Indicador Simbolico'),
        ),
        migrations.AddField(
            model_name='proyecto_tecnologico',
            name='txt_social_Indicador',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Indicador Social'),
        ),
    ]
